### ISSUE TITLE
Project executable

### ISSUE THREAD

**Issue by Surajj4837-th** [ros-visualization/rqt_image_view#56] opened 2021-09-09 07:04 UTC
This project is in C++, why it has created a py file as executable?
Can a normal executable file be created for this project?

**Comment by ablasdel** [comment] 2021-09-10 03:26
This project isn't intended to stand on its own it is a plug-in to the rqt framework. 

Can you share more about why you want this?

**Comment by Surajj4837-th** [comment] 2021-09-10 09:19
I have worked earlier in Qt and I just started to develop UI in ROS environment, I took your project to analyze and see the components used to understand ROS-Qt integration. In Qt, the Qt Creator generated a normal executable file and I was confused why you are not doing the same.

**Comment by ablasdel** [comment] 2021-09-10 14:40
I'd urge you to review the rqt framework as a whole that was designed and implemented to enable both python and C++ plugins. 

https://github.com/ros-visualization/rqt

Having a "why was the entire plug-in framework designed like this" on a single plug-in repo feels like the wrong place. I'm going to close this issue on this individual plug-in.

Please feel free to open an issue on the rqt repo to continue the conversation. Thanks

**Closed** 2021-09-10 14:41 UTC

**Comment by 130s** [comment] 2022-01-15 12:15
FYI, there's a standalone tool [image_view](http://wiki.ros.org/image_view) that pre-existed before rqt version (note, this isn't always the case with all `rqt`-based tools).
Both are not sharing the code base as explained by one of the original authors https://github.com/ros-perception/image_pipeline/issues/158
